### ISSUE TITLE
Refering to newly installed gnu radio next branch

### ISSUE THREAD

**Issue by jabirshabbir** [bastibl/gr-ieee802-11#107]
Hi bastil,
I facing some trouble as I am quite naive to installation and libraries in linux.As you mentioned that one should build the next branch of gnu radio with the next branch of gr-foo.I already have defult gnuradio installed on my PC.I have build and  installed the next branch of gnuradio but have'nt uninstalled the default one but how do I get the source code of gr-foo pointing to the new installed gnuradio.
Thanks in advance

**Comment by bastibl** [comment]
just uninstall the one from the package manager. If you haven't much experience with compiling stuff, it will only cause troubles.  If you have only one installation, the OOT module will find it automatically.

**Comment by jabirshabbir** [comment]
Thanks a lot.I uninstalled the default gnuradio and build the next branch of gnuradio suceesfully.But it shows these errors in make test
The follwing test failed
qa_qtgui (Failed)
qa_zeromq_sub (Failed).

Yet I am successfully able to install gnuradio by sudo make install 

I am also able to build and install gr-foo and gr-ieee802-11 succesfully.
But when I open the wifi_loopback.grc or wifi_rx.grc , gnuradio crashes.
I also noticed that wifi_loopback.py and wifi_rx.py are not generated after installation.
Is it true that the gr-ieee802-11 is not build correctly.
Although I tried  by deleting  CMakeCache.txt and also clean building it several times but it does'nt help

**Comment by bastibl** [comment]
The flow graphs are not automatically generated.

It's hard to tell what's going on if all you write is that is crashes. The easiest way to see what's the problem might be to import the Python modules of gr-foo and gr-ieee802-11 in an interactive session. 

Since it was a bit a chaotic installation process, I assume that there are some left-overs from previous attempts. Maybe the modules are compiled against the new GNU Radio installation, but use old libraries during runtime.
