### ISSUE TITLE
Long training Sequence

### ISSUE THREAD

**Issue by wshe1** [bastibl/gr-ieee802-11#126]
Dear bastibl:
    I read your program and encountered some problems, I would like to ask you.I want to know how the training sequence of the time domain training in the receiving receiver is obtained. I used the long training sequence you provided to pass the IFFT function and did not get the long training sequence of the time domain.I want to know how you got the long training sequence in the time domain.
 the long training sequence:
![screenshot from 2018-07-26 20-04-29](https://user-images.githubusercontent.com/33091503/43300259-b3b5fc88-9190-11e8-9cb4-7c69cdcb44b8.png)

the long training sequence in the time domain.
![screenshot from 2018-07-26 20-09-26](https://user-images.githubusercontent.com/33091503/43300287-e07dc494-9190-11e8-9ed8-5a3d8aeb8776.png)

**Comment by bastibl** [comment]
Hello wshe1. The first script calculates the training sequence that has to be put in the Carrier Allocator Block on TX side. IIRC it does some strange processing with the preamble, so this had to be compensated for, in order to use the block.

The sequence from the second screenshot is calculated with the `utils/create_long.R` script. Except for scaling it should match with the values in the standard.
