### ISSUE TITLE
Get specific constellation

### ISSUE THREAD

**Issue by gordon4067** [bastibl/gr-ieee802-11#140]
Dear Bastian Bloessl, 
I'm using gr-ieee802-11 to get pcap file and I am really getting same SSID or MAC address from your work. I really appreciate it.

I'm doing some research to get different WiFi AP's constellation recently.
The first problem is how to divide signals from many WiFi AP which use the same channel.
I got a big step towards from your work, I got different SSID from different WiFi AP.
There is only one step to complete my research, there are some questions I want to ask you.
I got SSID from the signals so I suppose that I extract the specific WiFi AP's information already.
Does it possible to reverse specific WiFi AP's information to the constellation data and how to do it?
If I could reverse the information, that means I can get different WiFi AP's constellation.

Please forgive my poor English ability. 

Sincerely, Gordon

**Comment by bastibl** [comment]
I'm not sure if I understand you correctly. I think you want to collect complex subcarrier constellations per device (i.e. AP or client). The problem is, at that stage where constellation are considered, the data is not yet decoded, which means that the sender MAC is not know. I'd suggest you use a tag to attach the complex constellations to the frame. Similar to what is done with the SNR estimate. It's done around here:
https://github.com/bastibl/gr-ieee802-11/blob/next/lib/frame_equalizer_impl.cc#L212

At a later stage (when the data is decoded and the sender MAC is available) you can access the complex constellations to do whatever.
