### ISSUE TITLE
UHD USRP Sink Module Failed

### ISSUE THREAD

**Issue by khg2478** [bastibl/gr-ieee802-11#150]
![screenshot from 2019-01-26 14-19-29](https://user-images.githubusercontent.com/2188129/51782962-6de31680-2175-11e9-89af-68534a17e1ae.png)

Hi. I have installed and tested uhd and gnuradio libraries using apt-get. However, UHD USRP Sink module fails with this error message below.

"Param - Ch0: Center Freq (Hz)(center_freq0):
	Value "uhd.tune_request(freq, rf_freq = freq - lo_offset, rf_freq_policy=uhd.tune_request.POLICY_MANUAL)" cannot be evaluated:
	name 'uhd' is not defined"

I have set up the same environment in another laptop and it works fine. However, I do not understand what is wrong with this error.

Could you tell me how I can solve this problem? Thanks.

**Comment by bastibl** [comment]
This is strange. I never installed UHD with apt. You could try to manually add an import block and add uhd manually (`from gnuradio import uhd`). Or you could open a Python interpreter and do `from gnuradio import uhd` to make sure that the module is correctly installed.

Also check that you don't have any broken Python configs (PYTHONPATH, etc).

If that doesn't help to solve the problem, I'd suggest to also ask on the GNU Radio mailing list, since the problem doesn't seem to be directly related to this module, but an issue of GNU Radio.
