### ISSUE TITLE
Limiting the OFDM carrier allocator max output items

### ISSUE THREAD

**Issue by giosalv** [bastibl/gr-ieee802-11#162]
Hi Bastian,

I am currently playing around with this code and measuring the performance the various blocks provided. One issue that I see is that the carrier allocator used in the wifi_phy_hier block is consuming a the majority of the execution time because the number of output items is very large (noutput_items is about 200k items by default). This causes the call to memset in the allocator to touch about 100MB on every call to the work function which causes many misses in the CPU's cache.

I would like to see if you have any insights about correctness issues by setting a limit to noutput_items for this application. According to this [documentation](https://www.gnuradio.org/doc/doxygen/page_operating_fg.html), fixing the max for this value is just a matter of latency versus throughput of the flowgraph. Would it be reasonable to set this to some much lower value (for, say, the wifi_loopback example), and if so, within what range?

Thanks.

**Comment by bastibl** [comment]
This came already up several times:
- https://github.com/bastibl/gr-ieee802-11/issues/146#issuecomment-447776917
- https://github.com/bastibl/gr-ieee802-11/pull/32

In short:
- The transmitter is not optimized for performance
- The problem is the upstream GNU Radio Carrier Allocator
- I think it would be better to improve the upstream allocator than to fork one
- The output buffer has to be huge to fit a maximum sized frame. It cannot be shorter since it is a TaggedStream block, i.e., a block that has to fit the whole frame in its input buffer before processing.
- BUT, AFAIS, the time-consuming memset is only done for the number of samples of the current frame: https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/ofdm_carrier_allocator_cvc_impl.cc#L159
