### ISSUE TITLE
unable to connect wifi in mobile

### ISSUE THREAD

**Issue by Venkyvulpine** [bastibl/gr-ieee802-11#222]
Hi,
Requirements I Use:
1. usrp n210 device
2. ubuntu 

When i run wifi_tx.grc its works fine but the wifi generated in the n210 is not visible in mobile device(samsung device).

what i tried so far:
1.changed different frequency and tried.
2.changed lo offset (increased)
3.changed pad front frame(increased)
Did all the above but its not detected by mobile.

FYI: 
1.n210 Device is underrunning.
2. the wifi is visible(connectable) by another usrp n210 device.

Questions
1.What may be the problem?
2.Can we really connect wifi with mobile using n210?
3. Does underrunning cause this problem?

wifi_tx.grc flow graph attached.
![wifi_tx grc](https://user-images.githubusercontent.com/40510883/81931344-8fd10880-9607-11ea-90c0-5d34e9d2aa51.png)

**Comment by bastibl** [comment]
This is a physical layer implementation that can be used to send standard compliant WLAN frames. It is not a complete WLAN stack that can be used like normal WLAN device, i.e., you cannot connect to an AP etc. Therefore, I have no idea what you mean with "connectable from a N210".

I am also not sure what you are expecting to see... It will only show up on your phone if you are sending a WLAN beacon. Are you doing this in the first place?

To debug this, just put a normal WLAN card in monitor mode an check if you can receive frames. Then you'll know if the problem is the transmitter or the fact that you don't send a valid beacon.
