### ISSUE TITLE
How to caputre Wifi preamble?

### ISSUE THREAD

**Issue by antittelbaugh** [bastibl/gr-ieee802-11#283]
I am currently using the tx and rx files in the examples to transmit and receive the Wi-Fi signal. I added a QT GUI time sink to the transmission graph and can clearly see the preamble however adding it on the receiving side I am not seeing it, though Wireshark is receiving it the preamble. I have tried file sink at multiple points in the flow diagram to then analyze in MATLAB and I still cannot see a clear preamble. Any tips?
Thank you

**Comment by bastibl** [comment]
I'm not sure what exactly you expect to see. What you can see is the plateau of the autocorrelation of the short training sequence. The RX flowgraph has QT Time Sink after the Divide block. You can add a trigger at ~0.6 and you should clearly see the plateu.
Alternatively, you can add a Time Sink with a trigger right after the SDR Source. In this case, you have to manually adjust the level since it depends on the RSSI, gain, etc.
