### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by SUSSdeveloper** [bastibl/gr-ieee802-11#304]
Hi,
Thanks for your effort to keep this project updated.
My first question: Is this project implementation of WiFi? I mean is it possible to have a IEEE802.11 network with one USRP N210 and some laptops?

During installation, I also received the below error.
CMake Error at swig/CMakeLists.txt:34 (include)
include could not find load file: GrSwig
Unknown CMake command command "GR_SWIG_MAKE"

Any help and support will be appreciated.

**Comment by bastibl** [comment]
This an IEEE 802.11 a/g/p transceiver for GNU Radio. Interoperability was tested with many off-the-shelf WiFi cards and IEEE 802.11p prototypes, setting the devices in monitor mode. It's a PHY implementation, i.e., it's not a full WLAN card since it doesn't meet timing requirements of the WLAN standard (e.g., send ACKs in time).
The error suggests that you tried to install the `maint-3.8` branch of this module with GNU Radio 3.9. But you'd have to provide much more information, to allow helping you.

**Comment by antonott** [comment]
@MahdiArghavani Just a friendly warning about using the N210 together with regular wifi-cards (the laptops):

Consumer wifi devices (such as laptop wifi-cards) operate at a sample rate of 20 MS/s, and as such you will have to use 20 MS/s on the N210 as well. However, due to hardware limitations of the N210, this will give you an odd decimation factor, which in turn will give you what is sometimes called "CIC rolloff". You can read a detailed description of the issue [here](https://witestlab.poly.edu/blog/why-does-my-received-spectrum-droop-at-the-edges/). This has nothing to do with gr-ieee802-11, but it is a limitation of the N210.

However, depending on what your goals are, this might not be a problem. My experience is that messages still go through fine, but it does affect more detailed measurements of channel parameters (because it warps the spectrum a little bit), such as CFO, CSI etc.
