### ISSUE TITLE
 PC connect the WiFi signal (sent by the USRP)

### ISSUE THREAD

**Issue by Leoplt** [bastibl/gr-ieee802-11#313]
hello,Can the PC connect the WiFi signal sent by the USRP device through the wireless network card for communication?

**Comment by bastibl** [comment]
I'm not sure what exactly your asking for. You can send and receive any frame. But you cannot associate to an AP (since it's not connected to a complete WLAN MAC stack). Also the PHY will never be fully-standard compliant (on higher layers) since it doesn't meet all timing requirements (e.g. responding to an ACK in time).
