### ISSUE TITLE
tx.grc

### ISSUE THREAD

**Issue by mbalalzade** [bastibl/gr-ieee802-11#363]
hi again
i have question about tx mode. i want to know when i run tx.grc  and i search for wifi networks by my phone i cant find any network. can u help me how can i use this repository as wifi modem that i can connect to it by phone. i think this repository works  between two sdr devices and not like a wifi modem. please help me.

**Comment by bastibl** [comment]
This came up several times. Please search the issues. In short, you'll have to use scapy to send a beacon and inject it into the transmitter. Set sample rate to 20MHz. If it doesn't work, try different gains etc. You will, however, not be able to connect to the SDR, since this is just a PHY implementation, which a complete WiFi stack on top of it.
