### ISSUE TITLE
performance issue on mcs 6 (rate 48Mbps)

### ISSUE THREAD

**Issue by cloud9477** [bastibl/gr-ieee802-11#375]
Hi, I did a simple test on performance (packet delivery ratio vs SNR), the curve of mcs 6 (legacy rate 48 mbps) is weird, I was using the equalizer 0, attached please find my results:

psdu len 114:
![wime-114](https://user-images.githubusercontent.com/13716674/236064608-83240763-3e0f-423b-9237-7f91c38a0086.png)

psdu len 264:
![wime-264](https://user-images.githubusercontent.com/13716674/236064716-99ec54cc-1c40-45b7-ad00-159b41ceeabf.png)

psdu len 564:
![wime-564](https://user-images.githubusercontent.com/13716674/236064771-f9258a43-8ea4-45d7-bcdb-42253dc8d6d4.png)

**Comment by bastibl** [comment]
did you run this with the most recent maint-3.10 branch?

**Comment by cloud9477** [comment]
yes

**Comment by bastibl** [comment]
Since this is the only MCS with a code rate of 2/3, I'd assume that there is an issue with certain frame sizes for this MCS. You could (1) use the generic decoder and see if it shows the same behavior or (2) look into rate-specific parts of the code, e.g., https://github.com/bastibl/gr-ieee802-11/blob/maint-3.8/lib/viterbi_decoder/base.cc#L39-L59

**Comment by cloud9477** [comment]
OK, I'll check and see if i could fix it.

**Comment by bastibl** [comment]
Did you find the reason for the strange behavior?

**Comment by cloud9477** [comment]
> Did you find the reason for the strange behavior?

Not yet, I try to decode the bits from the equalizer with my decoder, the performance is similar, and also I check the equalizer and seems no issue there. I guess maybe it's just the hard bits lost too much information.
